### PR TITLE
Feat/HDF 83 release vested rewards

### PR DESCRIPTION
**Pull request by mystbrent**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

- Added customizable scheduled task to trigger Rewards.releaseVestedRewards()
- Added option to pass deployer's wallet credentials via node arguments

### Changes to Core Features:

- Added hardhat configurations and smart contracts in the source code

### CODE REVIEW

**Review by tracyarciaga — CHANGES_REQUESTED** [review]
@mystbrent please add the following files on your feature branch:
1. https://github.com/HaloDAO/halo-rewards/blob/develop/CONTRIBUTING.md
2. commit template  -> https://github.com/HaloDAO/halo-rewards/tree/develop/.github
3. PR template -> https://github.com/HaloDAO/halo-rewards/tree/develop/.github
4. troublehooting.md -> https://github.com/HaloDAO/halo-rewards/blob/develop/docs/troubleshooting.md (please edit this)

**Review by ctverceles — CHANGES_REQUESTED** [review]
@mystbrent good start! worker pointed to kovan works great! Rewards contract deployed and you can see `releaseVestedRewards` calls in txs here https://kovan.etherscan.io/address/0x4749914dbfB8121783Dd5126bD22FcD795B440e0 

- [ ] just the comments on running locally. 
- [ ] let's also switch over to a git sub repo for the `halo-rewards` repo to keep it in sync

**Review by bitcoinbrisbane — APPROVED** [review]
Lots of formatting and style to discuss.  Lets merge and agree on standards

**Review by tracyarciaga — CHANGES_REQUESTED** [review]
Hi @mystbrent can you put the CONTRIBUTING.md outside the .github folder

**Pull request merged**
